[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "detecting-melanoma"
version = "0.1.0"
description = "Detecting melanoma with deep learning"
readme = "README.md"
authors = [
    { name = "Weston King-Leatham", email = "westonkingl1@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "albumentations",
    "flask",
    "numpy",
    "pandas",
    "pillow",
    "pretrainedmodels",
    "scikit-learn",
    "torch",
    "torchvision",
    "wtfml",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "pytest",
    "ruff",
]

[tool.setuptools]
py-modules = ["api", "create_folds", "main"]

[tool.setuptools.package-data]
"*" = ["templates/*"]
